title: California Privacy Directory
description: A collection of links to request personal data for companies under the California Consumer Privacy Act (CCPA).
repository: https://github.com/caprivacy/caprivacy
img: img/logo.svg
sass:
    style: compressed
permalink: pretty
markdown: kramdown
